name: Build bcm2712 aarch64
on:
   workflow_dispatch:
jobs:
    build:
        name: Build bcm2712
        runs-on: ubuntu-24.04-arm
        steps:
            - name: Setup Ubuntu
              run: |
                sudo apt update
                sudo apt install -y subversion build-essential gettext 2to3 python3-pyelftools python3-distutils-extra
            - name: Setup Go
              uses: actions/setup-go@main
              with:
                go-version: '1.25.4'
            - name: checkout
              uses: actions/checkout@main
            - name: Build
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cp -rf r3/kernel.patch openwrt/
                cp -rf r3/pm.patch openwrt/
                cd openwrt
                wget https://patch-diff.githubusercontent.com/raw/openwrt/openwrt/pull/19388.patch
                git apply 19388.patch
                sed -i -E 's;git.openwrt.org/(feed|project);github.com/openwrt;' feeds.conf.default
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd  feeds/packages
                wget https://github.com/mj22226/packages/commit/002334b3e5c8eb6969141aa243a10a835fee1d18.patch
                git apply 002334b3e5c8eb6969141aa243a10a835fee1d18.patch
                cd -
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                wget https://github.com/mj22226/openwrt-arm64/releases/download/bcm2712-20.1.8/llvm-bpf-20.1.8.Linux-aarch64.tar.zst
                tar -xvf llvm-bpf-20.1.8.Linux-aarch64.tar.zst
                wget https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2712/config.buildinfo -O .config
                echo "CONFIG_BUILD_LOG=y" >> .config
                echo "CONFIG_PACKAGE_luci=y" >> .config
                echo "CONFIG_PACKAGE_tini=y" >> .config
                echo "CONFIG_PACKAGE_kmod-usb-net-rtl8152=y" >> .config
                echo 'CONFIG_GOLANG_EXTERNAL_BOOTSTRAP_ROOT="/opt/hostedtoolcache/go/1.23.5/arm64/bin"' >> .config
                make defconfig
                make download -j32
                make -j$(nproc) 'IGNORE_ERRORS=n m' || true
                tar -czvf bin/targets/bcm27xx/bcm2712/logs.tar.gz logs || true
                rm -rf bin/targets/bcm27xx/bcm2712/packages || true
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
            - name: Delete tag
              uses: ClementTsang/delete-tag-and-release@main
              with:
                delete_release: true
                tag_name: bcm2712-6.12
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create release
              uses: ncipollo/release-action@main
              with:
                allowUpdates: true
                name: RPi 5 Firmware Images ${{ env.D }}
                tag: bcm2712-6.12
                replacesArtifacts: true
                makeLatest: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/bcm27xx/bcm2712/*
