name: Build Kernel

on:
  workflow_dispatch:
jobs:
  create_tar:
    name: Create kernel tar
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Pack kernel
        run: |
             wget https://github.com/mj22226/linux/archive/linux-6.19.tar.gz
             tar -xf linux-6.19.tar.gz
             mv linux-linux-6.19 linux-6.19.0
             tar -c linux-6.19.0 | xz -T0 > linux-6.19.0.tar.xz
             sha256sum linux-6.19.0.tar.xz > sha256sum

      - name: Release build artifacts
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          prerelease: false
          name: kernel 6.19.0
          tag: v6.19
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
                    *.xz
                    *.sha256sum
